
skillMetadata:
  sections:
    - name: Defaults
      fields:
        - name: default_speaker
          type: text
          label: the default speaker to use
          value: "Kitchen"
        - name: spotify_username
            type: text
            label: Your spotify username if you have an account
            value: "spotify"
        - name: spotify_client_id
            type: text
            label: Spotify client ID for api calls
            value: ""
        - name: spotify_client_secret
            type: text
            label: Spotify client secret for api calls
            value: ""
